### ISSUE TITLE
Main Chat

### ISSUE THREAD

**Issue by TheKnightGamer** [Inactive-to-Reactive/PluginSchoolV2#1]
I will be helping by making a new plugin tutorial for the website.

**Comment by remotevase** [comment]
:(

**Comment by remotevase** [comment]
Not now please

**Comment by TheKnightGamer** [comment]
I will just update @Taki21 own and add some new tutorials and @Taki21 tutorials will stay.

**Comment by remotevase** [comment]
I'm making taking active again via YouTube... No need

**Comment by TheKnightGamer** [comment]
But I will still help Taki with the tutorials

**Comment by remotevase** [comment]
Sure.....

**Comment by TheKnightGamer** [comment]
Could we instead make like a teaching system instead of just puting volumes.

**Comment by remotevase** [comment]
Maybe.... Not yet, though

**Comment by remotevase** [comment]
Thats FAR into the future
